=== jgommes1501/UD4_LMSGI/UD4/Actividad 5/datos.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nif, resultado, observaciones?, ip?, mac?)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT mac (#PCDATA)>
<!ATTLIST alumno 
    ip_required CDATA #IMPLIED
    mac_required CDATA #IMPLIED>

=== jgommes1501/UD4_LMSGI/UD4/Actividad 5/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "datos.dtd">
<alumnos>
    <alumno>
        <nif>12345678A</nif>
        <resultado>apto</resultado>
        <observaciones>Buen rendimiento</observaciones>
        <ip>192.168.0.1</ip>
    </alumno>
    <alumno>
        <nif>23456789B</nif>
        <resultado>no apto</resultado>
        <ip></ip>
        <mac>00:1A:2B:3C:4D:5E</mac>
    </alumno>
</alumnos>
