=== jgommes1501/UD4_LMSGI/UD4/Actividad 2/concesionario.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT concesionario (coche+)>
<!ELEMENT coche (codigo, marca, modelo, matricula, potencia, plazas, num_puertas)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT num_puertas (#PCDATA)>

=== jgommes1501/UD4_LMSGI/UD4/Actividad 3/concesionario.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE concesionario SYSTEM "concesionario.dtd">
<concesionario>
    <coche>
        <codigo>001</codigo>
        <marca>Ford</marca>
        <modelo>Focus</modelo>
        <matricula>1234ABC</matricula>
        <potencia>150</potencia>
        <plazas>5</plazas>
        <num_puertas>5</num_puertas>
    </coche>
    <coche>
        <codigo>002</codigo>
        <marca>BMW</marca>
        <modelo>320i</modelo>
        <matricula>5678XYZ</matricula>
        <potencia>180</potencia>
        <plazas>5</plazas>
        <num_puertas>5</num_puertas>
    </coche>
    <coche>
        <codigo>003</codigo>
        <marca>Audi</marca>
        <modelo>A4</modelo>
        <matricula>4321XYZ</matricula>
        <potencia>190</potencia>
        <plazas>5</plazas>
        <num_puertas>4</num_puertas>
    </coche>
    <coche>
        <codigo>004</codigo>
        <marca>Volkswagen</marca>
        <modelo>Golf</modelo>
        <matricula>8765JKL</matricula>
        <potencia>130</potencia>
        <plazas>5</plazas>
        <num_puertas>5</num_puertas>
    </coche>
</concesionario>
